apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: shivam
  creationTimestamp: null
  name: pod-master
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
